version: '3'
services:
  mailhog-testing:
    image: mailhog/mailhog:latest
    logging:
      driver: 'none'
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - mailhog_network
  php-mailhog-testing:
    image: php:8.0-cli
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - mailhog_network
    container_name: php-mailhog-testing

networks:
  mailhog_network:
    driver: bridge