services:
  mailhog-testing:
    image: mailhog/mailhog:latest
    container_name: ubuntu-mailhog-testing
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - mailhog-api-testing-network
  php8.4-mailhog-testing:
    build:
      context: .
      dockerfile: docker/php8.4/Dockerfile
    container_name: php8.4-mailhog-testing
    user: "1000:1000"
    working_dir: /var/www
    volumes:
      -   ./:/var/www
    networks:
      - mailhog-api-testing-network
    depends_on:
      - mailhog-testing
  php8.3-mailhog-testing:
    build:
      context: .
      dockerfile: docker/php8.3/Dockerfile
    container_name: php8.3-mailhog-testing
    user: "1000:1000"
    working_dir: /var/www
    volumes:
      -   ./:/var/www
    networks:
      - mailhog-api-testing-network
    depends_on:
      - mailhog-testing
  php8.2-mailhog-testing:
    build:
      context: .
      dockerfile: docker/php8.2/Dockerfile
    container_name: php8.2-mailhog-testing
    user: "1000:1000"
    working_dir: /var/www
    volumes:
      -   ./:/var/www
    networks:
      - mailhog-api-testing-network
    depends_on:
      - mailhog-testing
  php8.1-mailhog-testing:
    build:
      context: .
      dockerfile: docker/php8.1/Dockerfile
    container_name: php8.1-mailhog-testing
    user: "1000:1000"
    working_dir: /var/www
    volumes:
      -   ./:/var/www
    networks:
      - mailhog-api-testing-network
    depends_on:
      - mailhog-testing
  php8.0-mailhog-testing:
    build:
      context: .
      dockerfile: docker/php8.0/Dockerfile
    container_name: php8.0-mailhog-testing
    user: "1000:1000"
    working_dir: /var/www
    volumes:
      -   ./:/var/www
    networks:
      - mailhog-api-testing-network
    depends_on:
      - mailhog-testing
  php7.4-mailhog-testing:
    build:
      context: .
      dockerfile: docker/php7.4/Dockerfile
    container_name: php7.4-mailhog-testing
    user: "1000:1000"
    working_dir: /var/www
    volumes:
      -   ./:/var/www
    networks:
      - mailhog-api-testing-network
    depends_on:
      - mailhog-testing
  php7.3-mailhog-testing:
    build:
      context: .
      dockerfile: docker/php7.3/Dockerfile
    container_name: php7.3-mailhog-testing
    user: "1000:1000"
    working_dir: /var/www
    volumes:
      -   ./:/var/www
    networks:
      - mailhog-api-testing-network
    depends_on:
      - mailhog-testing

networks:
  mailhog-api-testing-network:
    driver: bridge
