version: "3"

services:
  mailhog-testing:
    image: mailhog/mailhog:latest
    container_name: ubuntu-mailhog-testing
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - mailhog-api-testing-network
  php-mailhog-testing:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php-mailhog-testing
    user: "${UID}:${GID}"
    working_dir: /var/www
    volumes:
      -   ./:/var/www
    networks:
      - mailhog-api-testing-network
    depends_on:
      - mailhog-testing

networks:
  mailhog-api-testing-network:
    driver: bridge
